all: build/all.xcodeproj local.json

local.json: local.json.default
	cp $^ $@

build/all.xcodeproj: build/gyp/gyp build/all.gyp
	build/gyp/gyp build/all.gyp --depth=.

build/gyp/gyp: 
	git clone https://chromium.googlesource.com/external/gyp.git build/gyp
